import React from 'react'

const Home = () => {
  return (
    <div style={{textAlign:"justify", margin:"20px",display:'flex',flexDirection:"column",justifyContent:'center',alignItems:'center'}}>
        {/* <img src="https://th.bing.com/th/id/OIP.wzrqLaESKSnQTYrUJ2gUYQHaGL?w=231&h=193&c=7&r=0&o=5&pid=1.7" alt="" height={"300px"} width={"300px"} /> */}
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium, sapiente. Molestias vero porro odit saepe. Porro laudantium voluptate explicabo magnam fuga, error illum adipisci enim at inventore quis laborum iure delectus possimus, sit iusto optio, natus alias sed corrupti. Quidem numquam blanditiis quisquam omnis et voluptatibus expedita hic est esse, amet rerum modi molestias ipsum asperiores quod at nisi quos molestiae? Totam aliquam praesentium vel officia iste fugiat sapiente corporis illum blanditiis expedita ea animi impedit velit explicabo vero, recusandae ut inventore non dicta dignissimos itaque molestiae exercitationem reiciendis magnam. Quam similique, minus commodi consequatur cum tempore cumque eligendi hic, quos ut, beatae iure in reiciendis provident! Praesentium id error quae alias tenetur reprehenderit obcaecati earum illum hic reiciendis omnis magnam, aperiam repudiandae odit quod illo nihil, dolorem voluptatem autem animi assumenda veritatis. Sequi, consequuntur? Illum, perspiciatis at aliquam non fugiat quam ut, dolores illo ex labore aspernatur numquam nostrum quis dolorem! Laboriosam quod tempora temporibus eligendi porro aliquam quae inventore ut commodi soluta ex, sapiente doloremque adipisci recusandae dicta esse corrupti. A dolor in ea iusto veniam nihil iure facere numquam, quasi provident sit est neque voluptate consequuntur asperiores, explicabo tempore. Natus quidem saepe, amet optio debitis unde libero?</p>
<br />
<br />
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sed debitis, nihil vel sequi fugiat dolorum, repellendus adipisci minima fuga numquam mollitia? Accusantium quasi, corporis fugiat odit nesciunt sunt doloremque nobis minus magni modi dicta asperiores maxime explicabo sint expedita dolore, sed officiis ut, laboriosam a id quo ab quis ullam. Atque nisi voluptatibus cum facilis obcaecati vel saepe animi modi, minima sapiente unde velit magnam, alias enim repellat corporis inventore cumque aliquid a quaerat! Et amet, recusandae minima repudiandae harum ipsum quam velit qui inventore, quia laborum veniam possimus veritatis cumque sint. Doloribus neque vel eos consequatur adipisci nisi labore repudiandae officiis, voluptate dignissimos eveniet? Sed, eveniet culpa cum et itaque laudantium ratione eius exercitationem rem delectus mollitia quos? Quaerat atque architecto iste molestias, dolore modi velit pariatur ipsa ab consectetur sit excepturi sunt ratione quos voluptas qui, illo impedit asperiores obcaecati explicabo voluptatibus nesciunt. At quos repellat ex adipisci? Reiciendis debitis ipsam quasi omnis inventore possimus, rerum expedita quibusdam illum non officia aspernatur aliquid id corrupti necessitatibus fugit optio obcaecati totam similique doloribus magni officiis doloremque? Ducimus veniam rerum reprehenderit earum at unde dolorem mollitia omnis dicta incidunt excepturi voluptate harum nisi cum sit, assumenda repudiandae tempora similique eaque?</p>
    </div>
  )
}

export default Home
